### ISSUE TITLE
VoodooInput

### ISSUE THREAD

**Issue by joeyave** [aspring14/Lenovo-Ideapad-S340-Hackintosh-Catalina-OpenCore#1]
What does Voodoo input do and what dragging bug are you talking about?

**Comment by VictorGamer072YT** [comment]
VoodooInput is the new kext for Magic Trackpad 2 emulation.

**Comment by aspring14** [comment]
**"An opensource trackpad aggregator kernel extension providing Magic Trackpad 2 software emulation for arbitrary input sources like VoodooPS2."**
https://github.com/acidanthera/VoodooInput

The trackpad bug was where when clicking down and dragging, then (unclicking) but while keeping your finger on the trackpad, you would keep dragging and after an amount of time it would stop, making dragging really inconsistent. Now, if you drag, you will keep dragging regardless of whether you are pressing down the trackpad, until you fully take your finger off the trackpad.
